config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resources :pages
  post 'pages/update_row_order' => 'pages#update_row_order'

  
  
  
  

end

app/models/page.rb
class Page < ActiveRecord::Base
  require 'open-uri'
  require 'nokogiri'
  include RankedModel
  ranks :row_order
  validates :word, presence: true, uniqueness: true
  
  def define (entry)
    # get_word = Page.find_by(word: entry.word)
    url = "http://www.dictionaryapi.com/api/v1/references/collegiate/xml/" + entry.word + "?key=68deb434-d334-44ef-9429-3f051a3a5fbd"
    doc = Nokogiri::HTML(open(url))
    definition = doc.css("dt")
    final_def = ""
    definition.each do |x|
    	x = x.to_s
    	num = x.index("<", 4)
    	final_def = final_def + "; " + x.slice(5..num-1)
	  end
	  entry.content = final_def.slice(1..-1)
	  entry.save
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
    def index
        # @pages_learning = Page.where(knowledge: "Learning")
        # @pages_learning = Page.where(knowledge: "Learning").order(:row_order)
        @pages_learning = Page.where(knowledge: "Learning").rank(:row_order).all
        @pages_learned = Page.where(knowledge: "Learned")
        @page = Page.where(knowledge: 'Learning').first
    end
    
    def update_row_order
        @word = Page.find(word_params[:word_id])
        @word.row_order = word_params[:row_order_position] #row_order_position?
        @word.save
        render nothing: true # this is a POST action, updates sent via AJAX, no view rendered
    end
    
    def new
        @page = Page.new
    end
    
    def edit 
      @page = Page.find(params[:id]) 
    end

    def update 
      @page = Page.find(params[:id]) 
      @page.update_attributes(page_params) 
      respond_to do |format|
        format.html {redirect_to(:back)}
        format.js 
      end
    end
    
    def refresh
      @page = Page.find(params[:id]) 
      @page.update(page_params) 
      redirect_to page_path(@page)
    end
    
    def show
      # if @page.nil?
      #   @page = Page.where(knowledge: 'Learning').first
      # else
      #   @next = Page.where("id > ?", params[:id]).order(:id).first 
      # end
      
      if params[:first] == 'true'
        @page = Page.where(knowledge: 'Learning').first
        # @next = Page.where("id > ?", @page.id).order(:id).first
      else
        @page = Page.where(knowledge: "Learning").where("id > ?", params[:id]).order(:id).first 
        # @next = Page.where("id > ?", @page.id).order(:id).first 
      end
      
      @practice_again = Page.where(knowledge: 'Learning').first
      
    end
    
    def destroy
      @page = Page.find(params[:id])
      @page.destroy
      redirect_to pages_path
    end
    
    def create 
      @page = Page.new(page_params)
      @page.define(@page)
      if @page.save 
        redirect_to pages_path
      else 
        render 'new' 
      end 
    end
    
    private 
        def page_params 
          params.require(:page).permit(:word, :content, :knowledge) 
        end
        
        def word_params
          params.require(:page).permit(:word_id, :row_order_position)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_errors.html.erb
<% if @page.errors.any? %>
  <div id="error_explanation">
  <div class="alert alert-danger">
    The form contains <%= pluralize(@page.errors.count, "error") %>.
    <ul>
    <% @page.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
    <h2 class="text-center"><%=link_to "Vocab Center", pages_path %></h2> 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>
  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/pages/edit.html.erb
<%= render "layouts/errors" %>
<div class = "row">
<div class = "col-sm-4 col-sm-offset-4 body">

<%= form_for @page do |f| %> 
  <div class="form-group">
    <%= f.label :page, "Edit Word" %><br> 
    <%= f.text_field :word, class: "form-control" %><br> 
    <%= f.text_area :content, rows: 10, class: "form-control"  %><br>
  </div>
    <div class="form-inline">
    <%= f.label :Learning, class:"radio-inline"%>
    <%= f.radio_button :knowledge, "Learning" %>
    <%= f.label :Learned, class:"radio-inline"%>
    <%= f.radio_button :knowledge, "Learned" %><br>
    </div>
  <div class="actions"> 
    <%= f.submit "Update", class: "btn btn-default" %> 
  </div> 
<%end%>

 <p><%= link_to "Home", pages_path %> </p>
</div>
</div>

app/views/pages/index.html.erb
<div class="main_links">
  <%= link_to 'Add Word', new_page_path, class: "btn btn-success" %> 
  <% if !@page.blank? %>
      <%= link_to 'Practice', page_path(@page, first: true), class: "btn btn-primary" %> 
  <%end%>
</div>

<% if @pages_learning.any? %>
<div class= "learning">  
<h3>Learning</h3> 
<table class="table table-hover" id="sortable"> 
  <% @pages_learning.each do |page| %> 
    <tr data-page-id=<%= "#{page.id}" %> class="todo" >
        <td id="the_word">
            <%= page.word %>
        </td>
        <td id="the_def">
            <%= page.content%>
        </td>
        <td id="the_delete">
            <%=link_to "", page_path(page), method: :delete, class: "glyphicon glyphicon-trash"%>
        </td>
        <td id="the_edit">
          <p><%= link_to "", edit_page_path(page), class: "glyphicon glyphicon-pencil" %></p>
        </td>
    </tr>
  <%end%>
  </table>
</div>
<%end%>


<% if @pages_learned.any? %>
<div class= "learned">
<h3> Learned <span id="hide"> Hide </span> </h3> 

  <table class="table table-hover display_learned"> 
    <% @pages_learned.each do |page| %> 
      <tr>
          <td id="the_word">
              <%= page.word %>
          </td>
          <td id="the_def">
              <%= page.content%>
          </td>
          <td id="the_delete">
              <%=link_to "", page_path(page), method: :delete, class: "glyphicon glyphicon-trash"%>
          </td>
          <td id="the_edit">
            <p><%= link_to "", edit_page_path(page), class: "glyphicon glyphicon-pencil" %></p>
          </td>
      </tr>
    <%end%>
  </table>
</div>
<%end%>

app/views/pages/new.html.erb
<%= render "layouts/errors" %>
<div class = "row">
<div class = "col-sm-4 col-sm-offset-4 body">
<%= form_for(@page) do |f| %> 
  <div class="form-group"> 
    <%= f.label :page, "New Word" %><br> 
    <%= f.text_field :word, class: "form-control" %><br> 

  </div> 
  <div class="actions"> 
    <%= f.submit "Create", class: "btn btn-default" %> 
  </div> 
<% end %>
</div>
</div>

app/views/pages/practice.html.erb
 <p> <%= @page.word %></p>
 <p>  <%= @page.content %></p>
<p><%= link_to "Next", page_path(@page) %></p>

app/views/pages/show.html.erb
<div class = "row">
<div class = "col-sm-4 col-sm-offset-4 body">
<% if @page%>
<div class="show_page">
 <p id="show_page_word"> <%= @page.word %></p>
 <button type="button" class="btn btn-primary" data-toggle="collapse" data-target="#demo">  
  Show Definition
</button>
<div id="demo" class="collapse">
  <div class="well"> <%= @page.content %>
  </div>
</div>
 <%= form_for @page, remote: true do |f| %> 
   <div class="form-inline practice">
    <%= f.label :Learning, class:"radio-inline"%>
    <%= f.radio_button :knowledge, "Learning" %>
    <%= f.label :Learned, class:"radio-inline"%>
    <%= f.radio_button :knowledge, "Learned" %><br>
    </div>
    <div class="actions">
    <%= f.submit "Update", class: "btn btn-default" %>
    </div>
 <%end%>


 
 <p class = "home_links">
  <%= link_to "Next", page_path(@page)%> |
  <%= link_to "Home", pages_path %> 
 </p>
 

 <% else %>

 <div class="btn-group btn-group-lg">
    <%= link_to "Home", pages_path, class: "btn btn-default"%>
    <%= link_to 'Practice Again', page_path(@practice_again, first: true), class: "btn btn-default" %> 
 </div>
 
 </div>
<%end%>
</div>
</div>